version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:17'
      timezone: Etc/UTC
    groups:
      dependencies:
        patterns: ['*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:23'
      timezone: Etc/UTC
    groups:
      actions:
        patterns: ['*']
